CREATE TABLE loan_accounts (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Auto-generated unique identifier',
    i_source_system_name VARCHAR(50) COMMENT 'I Source System Name | Values: BR.NET, FINACLE, VegaPay',
    d_state_name VARCHAR(50) COMMENT 'D State Name | Values: ODISHA, Odisha',
    i_branch_code INT COMMENT 'I Branch Code | Range: 50158 to 50158 | Constant value',
    i_branch_name VARCHAR(50) COMMENT 'I Branch Name | Values: ROURKELA | Constant value',
    i_loan_sourced_by_branch_code INT COMMENT 'I Loan Sourced By Branch Code | Range: 158 to 50158',
    i_gl_code BIGINT COMMENT 'I Gl Code | Range: 230020001 to 1100100040073',
    i_gl_name VARCHAR(50) COMMENT 'I Gl Name | 6 unique values',
    i_product_code VARCHAR(50) COMMENT 'I Product Code | e.g., GLS7, GLS5, VL65',
    d_product_name VARCHAR(100) COMMENT 'D Product Name | e.g., M33C - Monthly MAY\'2, TL06-Monthly June 22 | 0.1% NULL',
    d_product_group VARCHAR(50) COMMENT 'D Product Group | Values: UNSECURED, SECURED',
    d_loan_product_type VARCHAR(50) COMMENT 'D Loan Product Type | Values: JLG, IL, T NAGAR, OD Against FDR, VegaPay | 51.7% NULL',
    d_tl_cc_od_tagging VARCHAR(50) COMMENT 'D Tl Cc Od Tagging | Values: TL, OD',
    d_managed_owned VARCHAR(50) COMMENT 'D Managed Owned | Values: Owned, ARC, Managed, ARC 2',
    i_securitization_code INT COMMENT 'I Securitization Code | Range: 5500.0 to 99906.0 | 0.2% NULL',
    i_customer_id INT COMMENT 'I Customer Id | Range: 13 to 999983',
    i_customer_name VARCHAR(50) COMMENT 'I Customer Name | e.g., MI  BIBHAR, MUN  NISHA, BITA  DEVI',
    i_accountid_for_acid VARCHAR(50) COMMENT 'I Accountid For Acid | e.g., 33K00026, 28C00392, 65L00059',
    i_loan_series TINYINT COMMENT 'I Loan Series | Range: 1.0 to 2.0 | 0.1% NULL',
    i_sanctioned_limit INT COMMENT 'I Sanctioned Limit | Range: 0.0 to 200000.0',
    i_sanction_date DATE COMMENT 'I Sanction Date | From 2015-02-03 to 2026-01-10 | 0.0% NULL',
    i_first_disbursed_date DATE COMMENT 'I First Disbursed Date | From 2024-01-01 to 2025-12-31',
    i_disbursed_amount INT COMMENT 'I Disbursed Amount | Range: 0 to 200000',
    i_current_limit INT COMMENT 'I Current Limit | Range: 1000.0 to 450000.0',
    i_loan_maturity_date DATE COMMENT 'I Loan Maturity Date | From 2024-01-01 to 2027-03-31 | 0.0% NULL',
    d_tagging VARCHAR(50) COMMENT 'D Tagging | Values: FIXED, FLOATING, Fixed',
    i_rate_of_interest DECIMAL(7,3) COMMENT 'I Rate Of Interest | Range: 8.5 to 36.0',
    d_sub_sector_description VARCHAR(50) COMMENT 'D Sub Sector Description | Values: OTHER PRIORITY SECTOR, AGRICULTURE - SHORT TERM, AGRICULTURE - LONG TERM, OTHER NON PRIORITY SECTOR, SERVICES - MICRO ENTERPRISES-PS',
    i_purpose_code SMALLINT COMMENT 'I Purpose Code | Range: 0.0 to 825.0 | 0.1% NULL',
    i_purpose_category_code TINYINT COMMENT 'I Purpose Category Code | Range: 1.0 to 49.0 | 0.1% NULL',
    i_sector VARCHAR(50) COMMENT 'I Sector | Values: 156, O | 99.9% NULL',
    i_sub_sector VARCHAR(50) COMMENT 'I Sub Sector | Values: 690, NAO | 99.9% NULL',
    i_occu_code INT COMMENT 'I Occu Code | Range: 95019.0 to 95019.0 | Constant value | 99.9% NULL',
    i_gender VARCHAR(50) COMMENT 'I Gender | Values: F, M | 0.0% NULL',
    i_t_loan_purpose_description VARCHAR(50) COMMENT 'I T Loan Purpose Description | e.g., 13 - BI   CD Cassett, 129 - MSE   SE   Sma | 0.1% NULL',
    i_t_loan_purpose_category_description VARCHAR(50) COMMENT 'I T Loan Purpose Category Description | 9 unique values | 0.1% NULL',
    i_sector_desc VARCHAR(50) COMMENT 'I Sector Desc | Values: ALL OTHER NON PRIORITY | Constant value | 100.0% NULL',
    i_sub_sector_desc VARCHAR(50) COMMENT 'I Sub Sector Desc | Values: Other non priority Sector, NOT APPLICABLE | 99.9% NULL',
    i_acct_locn_code INT COMMENT 'I Acct Locn Code | Range: 50158.0 to 50158.0 | Constant value | 99.9% NULL',
    d_loan_purpose_name VARCHAR(100) COMMENT 'D Loan Purpose Name | e.g., ANY OTHER TYPE OF RT, SARI',
    d_constitution_name VARCHAR(50) COMMENT 'D Constitution Name | Values: INDIVIDUAL- FEMALE, INDIVIDUAL- MALE, DATA / VALUE NOT PROVIDED',
    d_caste_name VARCHAR(50) COMMENT 'D Caste Name | 7 unique values',
    d_religion_name VARCHAR(50) COMMENT 'D Religion Name | 8 unique values',
    d_occupation_name VARCHAR(50) COMMENT 'D Occupation Name | 11 unique values',
    d_bank_non_bank_tagging VARCHAR(50) COMMENT 'D Bank Non Bank Tagging | Values: Non Bank | Constant value',
    psl_non_psl VARCHAR(50) COMMENT 'Psl Non Psl | Values: Non PSL, PSL',
    d_psl_tagging VARCHAR(100) COMMENT 'D Psl Tagging | 11 unique values',
    d_bkspi_tagging VARCHAR(50) COMMENT 'D Bkspi Tagging | Values: Others, Agriculture, Professional and other services, Other personal loans',
    d_more_than_less_than_25lacs VARCHAR(50) COMMENT 'D More Than Less Than 25Lacs | Values: Less than 25 Lakh Advance | Constant value',
    i_emi_amount SMALLINT COMMENT 'I Emi Amount | Range: 0 to 10800',
    i_outstanding_principal DECIMAL(11,3) COMMENT 'I Outstanding Principal | Range: 0.0 to 177468.78',
    i_advance_emi_amount DECIMAL(10,3) COMMENT 'I Advance Emi Amount | Range: 0.0 to 11854.38',
    i_int_accrued_due DECIMAL(9,3) COMMENT 'I Int Accrued Due | Range: 0.0 to 4805.12 | 20.8% NULL',
    d_final_pos_balance DECIMAL(11,3) COMMENT 'D Final Pos Balance | Range: -1100.0 to 177468.78',
    i_securedunsecured VARCHAR(50) COMMENT 'I Securedunsecured | Values: Secured, Un-Secured',
    i_security_value INT COMMENT 'I Security Value | Range: 0 to 250000',
    d_used_security DECIMAL(11,3) COMMENT 'D Used Security | Range: 0.0 to 177468.78',
    d_secured_amt DECIMAL(11,3) COMMENT 'D Secured Amt | Range: 0.0 to 177468.78',
    d_un_secured_amt DECIMAL(11,3) COMMENT 'D Un Secured Amt | Range: 0.0 to 155000.0',
    d_net_balance_for_provision DECIMAL(11,3) COMMENT 'D Net Balance For Provision | Range: 0.0 to 177468.78',
    d_asset_class VARCHAR(50) COMMENT 'D Asset Class | 6 unique values',
    d_npa_date DATE COMMENT 'D Npa Date | From 2022-01-02 to 2023-12-31 | 79.3% NULL',
    d_unservied_int TINYINT COMMENT 'D Unservied Int | Range: 0.0 to 0.0 | Constant value',
    d_npa_reason VARCHAR(50) COMMENT 'D Npa Reason | Values: , DEGRADE BY OVERDUE, Link By AccountId 158TL0900014 | 79.3% NULL',
    i_overdue_since_dt DATE COMMENT 'I Overdue Since Dt | From 2024-01-01 to 2025-04-30 | 67.5% NULL',
    i_overdue_amt DECIMAL(10,3) COMMENT 'I Overdue Amt | Range: 0.0 to 87284.5',
    i_overdue_principal DECIMAL(10,3) COMMENT 'I Overdue Principal | Range: 0.0 to 64542.0',
    i_overdue_interest DECIMAL(10,3) COMMENT 'I Overdue Interest | Range: 0.0 to 30798.5',
    i_overdue_other TINYINT COMMENT 'I Overdue Other | Range: 0.0 to 0.0 | Constant value',
    i_review_due_dt DATE COMMENT 'I Review Due Dt | From 2024-04-12 to 2024-10-25 | 99.9% NULL',
    id_lastcr_dt DATE COMMENT 'Id Lastcr Dt | From 2025-02-11 to 2025-02-15 | 99.9% NULL',
    d_overdue_dpd SMALLINT COMMENT 'D Overdue Dpd | Range: 0 to 3383',
    d_intservice_dpd TINYINT COMMENT 'D Intservice Dpd | Range: 0 to 0 | Constant value',
    d_reviewdue_dpd SMALLINT COMMENT 'D Reviewdue Dpd | Range: 0 to 443',
    d_over_drawn_since_dpd TINYINT COMMENT 'D Over Drawn Since Dpd | Range: 0 to 0 | Constant value',
    d_stockst_dpd TINYINT COMMENT 'D Stockst Dpd | Range: 0 to 0 | Constant value',
    id_last_cr_date_dpd SMALLINT COMMENT 'Id Last Cr Date Dpd | Range: 0 to 329',
    d_accountmax_financial_dpd SMALLINT COMMENT 'D Accountmax Financial Dpd | Range: 0 to 3383',
    d_accountmax_non_financial_dpd SMALLINT COMMENT 'D Accountmax Non Financial Dpd | Range: 0 to 443',
    d_customermax_financial_dpd SMALLINT COMMENT 'D Customermax Financial Dpd | Range: 0 to 3383',
    d_customermax_non_financial_dpd SMALLINT COMMENT 'D Customermax Non Financial Dpd | Range: 0 to 443',
    d_restructure_tagging VARCHAR(50) COMMENT 'D Restructure Tagging | Values: Restructure | Constant value | 94.5% NULL',
    i_eclgs_tagging VARCHAR(50) COMMENT 'I Eclgs Tagging | Values: ECLGS | Constant value | 96.5% NULL',
    d_npa_prov_percent DECIMAL(8,3) COMMENT 'D Npa Prov Percent | Range: 0.0 to 100.0',
    d_npa_prov_amt DECIMAL(10,3) COMMENT 'D Npa Prov Amt | Range: 0.0 to 64542.0',
    i_restructure_prov_percent TINYINT COMMENT 'I Restructure Prov Percent | Range: 0.0 to 0.0 | Constant value | 94.5% NULL',
    d_restructure_prov_amt TINYINT COMMENT 'D Restructure Prov Amt | Range: 0.0 to 0.0 | Constant value | 98.2% NULL',
    d_additional_15_per_restructure_prov_percent TINYINT COMMENT 'D Additional 15 Per Restructure Prov Percent | Range: 0.0 to 0.0 | Constant value',
    d_additional_15_per_restructure_prov_amount TINYINT COMMENT 'D Additional 15 Per Restructure Prov Amount | Range: 0.0 to 0.0 | Constant value | 94.5% NULL',
    i_addl_provision_amount TINYINT COMMENT 'I Addl Provision Amount | Range: 0.0 to 0.0 | Constant value',
    d_total_provision DECIMAL(10,3) COMMENT 'D Total Provision | Range: 0.0 to 64542.0',
    d_final_provision_per DECIMAL(8,3) COMMENT 'D Final Provision Per | Range: 0.0 to 100.0',
    d_prov_per_secured DECIMAL(8,3) COMMENT 'D Prov Per Secured | Range: 0.25 to 100.0',
    d_prov_secured DECIMAL(8,3) COMMENT 'D Prov Secured | Range: 0.0 to 709.88',
    d_prov_per_unsecured DECIMAL(8,3) COMMENT 'D Prov Per Unsecured | Range: 0.25 to 100.0',
    d_prov_unsecured DECIMAL(10,3) COMMENT 'D Prov Unsecured | Range: 0.0 to 64542.0',
    d_sma_tagging VARCHAR(50) COMMENT 'D Sma Tagging | 9 unique values',
    d_sma_dt DATE COMMENT 'D Sma Dt | From 2025-10-14 to 2026-01-09 | 88.2% NULL',
    d_provision_std_percent DECIMAL(6,3) COMMENT 'D Provision Std Percent | Range: 0.0 to 0.4',
    d_provision_std_amt DECIMAL(8,3) COMMENT 'D Provision Std Amt | Range: 0.0 to 709.88',
    d_90_days_credit INT COMMENT 'D 90 Days Credit | Range: 0.0 to 821500.0',
    d_90days_interest SMALLINT COMMENT 'D 90Days Interest | Range: 0.0 to 3778.0',
    date_of_data DATE COMMENT 'Date Of Data | From 2017-01-10 to 2017-01-10 | Constant value',
    incremental_prov_amt DECIMAL(10,3) COMMENT 'Incremental Prov Amt | Range: 0.0 to 28177.5',
    incrementalprovper TINYINT COMMENT 'Incrementalprovper | Range: 0.0 to 50.0',
    d_bsr1code INT COMMENT 'D Bsr1Code | Range: 1109 to 99999',
    i_original_outstanding_principal DECIMAL(11,3) COMMENT 'I Original Outstanding Principal | Range: -1100.0 to 177468.78',
    fk_id BIGINT COMMENT 'Fk Id | Range: 1101202605382638 to 1101202612142914',
    as_on_dt DATE COMMENT 'As On Dt | From 2017-01-10 to 2017-01-10 | Constant value',
    i_eclgc_provision TINYINT COMMENT 'I Eclgc Provision | Range: 0.0 to 0.0 | Constant value',
    i_floating_provision TINYINT COMMENT 'I Floating Provision | Range: 0.0 to 0.0 | Constant value',
    i_originalsector_code VARCHAR(50) COMMENT 'I Originalsector Code | Values: O | Constant value | 99.9% NULL',
    i_originalsub_sector_code VARCHAR(50) COMMENT 'I Originalsub Sector Code | Values: NAO | Constant value | 99.9% NULL',
    d_psl_tagging_new VARCHAR(50) COMMENT 'D Psl Tagging New | Values: MSME - Micro - Services, Personal Loans under Non-Priority Sector | 63.1% NULL',
    i_originalacct_occp_code INT COMMENT 'I Originalacct Occp Code | Range: 95009.0 to 95019.0 | 99.9% NULL',
    ps_non_psl_new VARCHAR(50) COMMENT 'Ps Non Psl New | Values: PSL, Non PSL | 63.1% NULL',
    i_loan_type VARCHAR(50) COMMENT 'I Loan Type | Values: NONMFI, MFI | 0.1% NULL',
    i_sourceassetclass VARCHAR(50) COMMENT 'I Sourceassetclass | 10 unique values | 77.3% NULL',
    d_psl_tagging_final VARCHAR(100) COMMENT 'D Psl Tagging Final | 11 unique values',
    ps_non_psl_final VARCHAR(50) COMMENT 'Ps Non Psl Final | Values: Non PSL, PSL',
    i_cgfmu_covered_year VARCHAR(50) COMMENT 'I Cgfmu Covered Year | Values: 2025-26, 2024-25, 2023-24, 2022-23 | 30.2% NULL',
    i_cgfmu_scheme_active VARCHAR(50) COMMENT 'I Cgfmu Scheme Active | Values: YES, NO | 30.2% NULL',
    i_cgfmu_claimreceived_status VARCHAR(50) COMMENT 'I Cgfmu Claimreceived Status | Values: NO | Constant value | 30.2% NULL',
    i_cgfmu_claimreceived_amount TINYINT COMMENT 'I Cgfmu Claimreceived Amount | Range: 0.0 to 0.0 | Constant value',
    d_only_outstanding_principle DECIMAL(11,3) COMMENT 'D Only Outstanding Principle | Range: 0.0 to 177468.78',
    d_guaranteed_portion DECIMAL(23,16) COMMENT 'D Guaranteed Portion | Range: 0.0 to 75431.565',
    d_unguaranteed_portion DECIMAL(24,16) COMMENT 'D Unguaranteed Portion | Range: 0.0 to 177468.78',
    ad_psl_non_psld2k VARCHAR(50) COMMENT 'Ad Psl Non Psld2K | Values: PSL, Non PSL | 0.1% NULL',
    ad_d_psl_taggingd2k VARCHAR(100) COMMENT 'Ad D Psl Taggingd2K | 12 unique values | 0.1% NULL',
    ad_d_bsr1coded2k INT COMMENT 'Ad D Bsr1Coded2K | Range: 1109.0 to 99999.0 | 0.1% NULL',
    ad_d_bkspi_taggingd2k VARCHAR(50) COMMENT 'Ad D Bkspi Taggingd2K | Values: Professional and other services, Trade, Agriculture, Others, Other personal loans | 0.1% NULL',
    ad_psl_non_pslinternal VARCHAR(50) COMMENT 'Ad Psl Non Pslinternal | Values: Non PSL, PSL | 0.1% NULL',
    ad_psl_classificationinternal VARCHAR(100) COMMENT 'Ad Psl Classificationinternal | 11 unique values | 0.1% NULL',
    ad_bkspiinternal VARCHAR(50) COMMENT 'Ad Bkspiinternal | Values: Others, Professional and other services, Agriculture, Other personal loans | 0.1% NULL',
    ad_bsr_codeinternal INT COMMENT 'Ad Bsr Codeinternal | Range: 1109.0 to 93101.0 | 0.2% NULL',
    ad_bsr_descriptioninternal VARCHAR(50) COMMENT 'Ad Bsr Descriptioninternal | e.g., Other Retail Trade | 0.1% NULL',
    ad_mfiornonmfiinternal VARCHAR(50) COMMENT 'Ad Mfiornonmfiinternal | Values: NONMFI, MFI | 0.1% NULL',
    ad_udyam_regnointernal VARCHAR(50) COMMENT 'Ad Udyam Regnointernal | e.g., UDYAM-I-OD-30-434706, UDYAM-I-OD-30-293754, UDYAM-I-OD-30-727282 | 63.2% NULL',
    ad_agree_cost TINYINT COMMENT 'Ad Agree Cost | Range: 0.0 to 0.0 | Constant value | 100.0% NULL',
    ad_metro VARCHAR(50) COMMENT 'Ad Metro | Values: N | Constant value | 100.0% NULL',
    ad_acid VARCHAR(50) COMMENT 'Ad Acid | Values: ZZ3053276, ZZ5263749, ZZ5443029, ZZ8010617 | 99.9% NULL',
    ad_manual VARCHAR(50) COMMENT 'Ad Manual | Values: Y | Constant value | 99.9% NULL',
    ad_condition TINYINT COMMENT 'Ad Condition | Range: 1 to 100',
    r_secure_value DECIMAL(11,3) COMMENT 'R Secure Value | Range: 0.0 to 177468.78',
    r_unsecure_value DECIMAL(11,3) COMMENT 'R Unsecure Value | Range: 0.0 to 155000.0',
    product_sub_category VARCHAR(50) COMMENT 'Product Sub Category | Values: JLG, VL, Others, OD',
    final_sector_bifurcation VARCHAR(50) COMMENT 'Final Sector Bifurcation | Values: Micro Finance, Agriculture, Others',
    ad_slbcbranchcode INT COMMENT 'Ad Slbcbranchcode | Range: 50158 to 50158 | Constant value',
    ad_blockcode SMALLINT COMMENT 'Ad Blockcode | Range: 3586 to 3586 | Constant value',
    ad_branchblockname VARCHAR(50) COMMENT 'Ad Branchblockname | Values: RAJGANGPUR | Constant value',
    ad_slbc_statecode TINYINT COMMENT 'Ad Slbc Statecode | Range: 21 to 21 | Constant value',
    ad_slbc_statename VARCHAR(50) COMMENT 'Ad Slbc Statename | Values: ODISHA | Constant value',
    ad_slbc_districtcode SMALLINT COMMENT 'Ad Slbc Districtcode | Range: 373 to 373 | Constant value',
    ad_slbc_districtname VARCHAR(50) COMMENT 'Ad Slbc Districtname | Values: SUNDARGARH | Constant value',
    ad_slbc_customerlimit INT COMMENT 'Ad Slbc Customerlimit | Range: 22000.0 to 205000.0 | 14.7% NULL',
    ad_slbc_customerbalance DECIMAL(11,3) COMMENT 'Ad Slbc Customerbalance | Range: 0.0 to 155000.0 | 14.7% NULL',
    ad_slbc_tagging VARCHAR(50) COMMENT 'Ad Slbc Tagging | Values: Kishore, Shishu | 14.7% NULL',
    lifeinsurancepremium TINYINT COMMENT 'Lifeinsurancepremium | Range: 0.0 to 0.0 | Constant value',
    otherinsurancepremium TINYINT COMMENT 'Otherinsurancepremium | Range: 0.0 to 0.0 | Constant value',
    totalinsurancepremium TINYINT COMMENT 'Totalinsurancepremium | Range: 0.0 to 0.0 | Constant value',
    percentagetotalinsurancepremiumtosanctionamount TINYINT COMMENT 'Percentagetotalinsurancepremiumtosanctionamount | Range: 0.0 to 0.0 | Constant value',
    ad_insurancenet_balance_for_provision_psl DECIMAL(11,3) COMMENT 'Ad Insurancenet Balance For Provision Psl | Range: 0.0 to 155000.0',
    ad_insurancenet_balance_for_provision_non_psl DECIMAL(11,3) COMMENT 'Ad Insurancenet Balance For Provision Non Psl | Range: 0.0 to 177468.78',
    percent_total_insurance_premium_to_disburse_amount TINYINT COMMENT 'Percent Total Insurance Premium To Disburse Amount | Range: 0.0 to 0.0 | Constant value',
    insurancedisburse_for_provision_psl INT COMMENT 'Insurancedisburse For Provision Psl | Range: 0.0 to 200000.0',
    insurancedisburse_for_provision_non_psl INT COMMENT 'Insurancedisburse For Provision Non Psl | Range: 0.0 to 200000.0',
    PRIMARY KEY (id)
) ENGINE=InnoDB
ROW_FORMAT=DYNAMIC
DEFAULT CHARSET=utf8mb4
COMMENT='Generated from Excel: input.xlsx on 2026-01-13 08:06:42';